// Cart Action Types
export const FETCH_CART_FROM_SESSION = 'FETCH_CART_FROM_SESSION';
export const FETCH_CART_BY_ID = 'FETCH_CART_BY_ID';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_SHIPPING_TO_CART = 'ADD_SHIPPING_TO_CART';
export const CLEAR_OLD_CART = 'CLEAR_OLD_CART';

// Shopping-List Action Types
export const FETCH_LIST_FROM_SESSION = 'FETCH_LIST_FROM_SESSION';
export const FETCH_LIST_BY_ID = 'FETCH_LIST_BY_ID';
export const CREATE_LIST = 'CREATE_LIST';
export const ADD_TO_LIST = 'ADD_TO_LIST';
export const REMOVE_FROM_LIST = 'REMOVE_FROM_LIST';
export const CLEAR_OLD_LIST = 'CLEAR_OLD_LIST';
export const FETCH_USER_SHOPPING_LISTS = 'FETCH_USER_SHOPPING_LISTS';

// Order Action Types
export const SUBMIT_ORDER = 'SUBMIT_ORDER';
export const CLEAR_LAST_ORDER = 'CLEAR_LAST_ORDER';
export const FETCH_ORDER_FROM_SESSION = 'FETCH_ORDER_FROM_SESSION';
export const FETCH_ORDER_BY_ID = 'FETCH_ORDER_BY_ID';

// User Action Types
export const FETCH_USER_FROM_SESSION = 'FETCH_USER_FROM_SESSION';
export const FETCH_USER_BY_ID = 'FETCH_USER_BY_ID';
export const LOG_IN_USER = 'LOG_IN_USER';
export const LOG_OUT_USER = 'LOG_OUT_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const UPDATE_USER = 'UPDATE_USER';